### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by erinline** [yoraish/botello#2]
Disclaimer first: I'm building with ubuntu 18.04/ROS Melodic. However, the errors seem independent as far as I can tell.

Two build failures involving a `bool` return type not provided in the following files and methods:
File: Line 89 in botello_aruco_gridboard_node.cpp
Method: `bool BotelloArucoGridboardNode::getParamsFromParamServer()`
File: Line 53 in botello_aruco_node.cpp
Method: `bool BotelloArucoNode::getParamsFromParamServer()`

To just move forward I added `return true` to both these methods, but I still get a build failure in both the above packages.
In Botello aruco gridboard:
```
Errors     << botello_aruco_gridboard:make /home/erinline/src/botello/logs/botello_aruco_gridboard/build.make.002.log
CMakeFiles/botello_aruco_gridboard_node.dir/src/botello_aruco_gridboard_node.cpp.o: In function `botello_aruco_gridboard::BotelloArucoGridboardNode::imageCb(boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const> const&)':
botello_aruco_gridboard_node.cpp:(.text+0x2d05): undefined reference to `cv::aruco::detectMarkers(cv::_InputArray const&, cv::Ptr<cv::aruco::Dictionary> const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::Ptr<cv::aruco::DetectorParameters> const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&)'
botello_aruco_gridboard_node.cpp:(.text+0x2e6d): undefined reference to `cv::aruco::estimatePoseBoard(cv::_InputArray const&, cv::_InputArray const&, cv::Ptr<cv::aruco::Board> const&, cv::_InputArray const&, cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [/home/erinline/src/botello/devel/.private/botello_aruco_gridboard/lib/botello_aruco_gridboard/botello_aruco_gridboard_node] Error 1
make[1]: *** [CMakeFiles/botello_aruco_gridboard_node.dir/all] Error 2
make: *** [all] Error 2
cd /home/erinline/src/botello/build/botello_aruco_gridboard; catkin build --get-env botello_aruco_gridboard | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << botello_aruco_gridboard:make           [ Exited with code 2 ]
```

In botello aruco:
```
Errors     << botello_aruco:make /home/erinline/src/botello/logs/botello_aruco/build.make.002.log
/home/erinline/src/botello/src/botello/botello_ws/src/botello_aruco/src/botello_aruco_node.cpp: In member function ‘double botello_aruco::BotelloArucoNode::standardDeviation(std::vector<double>&)’:
/home/erinline/src/botello/src/botello/botello_ws/src/botello_aruco/src/botello_aruco_node.cpp:403:24: error: ‘accumulate’ is not a member of ‘std’
     double mean = std::accumulate(v.begin(), v.end(), 0.0) / v.size();
                        ^~~~~~~~~~
/home/erinline/src/botello/src/botello/botello_ws/src/botello_aruco/src/botello_aruco_node.cpp:403:24: note: suggested alternative:
In file included from /usr/local/include/opencv2/imgproc/imgproc.hpp:48,
                 from /opt/ros/melodic/include/cv_bridge/cv_bridge.h:44,
                 from /home/erinline/src/botello/src/botello/botello_ws/src/botello_aruco/include/botello_aruco_node.hpp:11,
                 from /home/erinline/src/botello/src/botello/botello_ws/src/botello_aruco/src/botello_aruco_node.cpp:1:
/usr/local/include/opencv2/imgproc.hpp:2644:19: note:   ‘cv::accumulate’
 CV_EXPORTS_W void accumulate( InputArray src, InputOutputArray dst,
                   ^~~~~~~~~~
/home/erinline/src/botello/src/botello/botello_ws/src/botello_aruco/src/botello_aruco_node.cpp:407:26: error: ‘inner_product’ is not a member of ‘std’
     double sq_sum = std::inner_product(diff.begin(), diff.end(), diff.begin(), 0.0);
                          ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/botello_aruco_node.dir/src/botello_aruco_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/botello_aruco_node.dir/all] Error 2
make: *** [all] Error 2
cd /home/erinline/src/botello/build/botello_aruco; catkin build --get-env botello_aruco | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```
This error was resolved by adding `#include <numeric>` to `botello_aruco_node.h`, so only the error in botello aruco gridboard remains. Advice?

**Comment by yoraish** [comment]
Hey @erinline! Thank you for being so thorough! I am glad you solved some of the initial build failures.
This seems to me like an OpenCV version mismatch problem, which could hopefully be solved quickly. Given that other packages that use the `aruco` namespace do pass the build for you, I am led to believe that you have it installed, just perhaps in a different version than mine. I am using OpenCV version 3.3.1-dev. Perhaps some helpful questions would be:

1. What version of OpenCV are you using? (You can check that in a python interpreter and running `import cv2 \print(cv2.__version__)`.
2. Is the signature that I used for `detectMarkers` and `estimatePoseBoard` similar to the one in your version's signature in the docs? https://docs.opencv.org/5.x/d9/d6a/group__aruco.html 

:robot:

**Comment by erinline** [comment]
Here is my opencv version output:
```
erinline@erinline-MacBookPro:~$ cat $(locate OpenCVConfig.cmake) | grep "SET(OpenCV_VERSION "
SET(OpenCV_VERSION @OPENCV_VERSION_PLAIN@)
SET(OpenCV_VERSION 3.3.1)
SET(OpenCV_VERSION 3.3.1)
SET(OpenCV_VERSION 3.3.1)
SET(OpenCV_VERSION 3.3.1)
SET(OpenCV_VERSION 3.3.1)
SET(OpenCV_VERSION 3.2.0)
```
What version do you have/recommend? And I'm not sure what you mean by signature.

I did try running just that command (bc the tello driver did build for me in that first step) but I don't see an image topic being created. Looks like I'm getting a crash in the tello driver:
```
setting /run_id to 0e727760-d44e-11ec-9ae5-f45c89a267e3
process[rosout-1]: started with pid [4723]
started core service [/rosout]
process[tello/tello_driver_node-2]: started with pid [4730]
process[botello_localization_node-3]: started with pid [4731]
process[map_to_tag0-4]: started with pid [4732]
[ INFO] [1652619226.625805385]: Instantiating BotelloLocalizationNode.
process[botello_navigation_node-5]: started with pid [4737]
process[botello_movement_node-6]: started with pid [4740]
[ INFO] [1652619226.640705625]: Init BotelloLocalizationNode done.
ERROR: cannot launch node of type [botello_aruco_gridboard/botello_aruco_gridboard_node]: Cannot locate node of type [botello_aruco_gridboard_node] in package [botello_aruco_gridboard]. Make sure file exists in package path and permission is set to executable (chmod +x)
[ INFO] [1652619226.655561007]: Instantiating BotelloNavigationNode.
[ INFO] [1652619226.658547863]: Read waypoint id: 0. x y z r p y [0 0 1 0 1.57 1.57], frame: tag0
[ INFO] [1652619226.658621939]: Read waypoint id: 3. x y z r p y [1.5 -1 0 0 0 0], frame: map
[ INFO] [1652619226.658673705]: Read waypoint id: 2. x y z r p y [1 -1 0 0 0 0], frame: map
[ INFO] [1652619226.658717349]: Read waypoint id: 1. x y z r p y [1 -1 0 0 0 -3.14159], frame: map
[ INFO] [1652619226.658758048]: Read waypoint id: 4. x y z r p y [0 0 1.5 0 1.57 1.57], frame: tag0
[ INFO] [1652619226.658815595]: Init BotelloNavigationNode done.
[ INFO] [1652619226.659069848]: Instantiating BotelloMovementNode.
[ INFO] [1652619226.678319452]: Init BotelloMovementNode done.
Traceback (most recent call last):
  File "/home/erinline/src/botello/src/botello/botello_ws/src/tello_driver/nodes/tello_driver_node", line 548, in <module>
    main()
  File "/home/erinline/src/botello/src/botello/botello_ws/src/tello_driver/nodes/tello_driver_node", line 542, in main
    robot = TelloNode()
  File "/home/erinline/src/botello/src/botello/botello_ws/src/tello_driver/nodes/tello_driver_node", line 95, in __init__
    self.log = RospyLogger('Tello')
  File "/home/erinline/src/botello/src/botello/botello_ws/src/tello_driver/nodes/tello_driver_node", line 42, in __init__
    super(RospyLogger, self).__init__(header)
TypeError: super() argument 1 must be type, not classobj
[ INFO] [1652619227.694687424]: Could not find goal transform for 1.01638 seconds. Exception:"base_link" passed to lookupTransform argument target_frame does not exist. 

[tello/tello_driver_node-2] process has died [pid 4730, exit code 1, cmd /home/erinline/src/botello/src/botello/botello_ws/src/tello_driver/nodes/tello_driver_node __name:=tello_driver_node __log:=/home/erinline/.ros/log/0e727760-d44e-11ec-9ae5-f45c89a267e3/tello-tello_driver_node-2.log].
log file: /home/erinline/.ros/log/0e727760-d44e-11ec-9ae5-f45c89a267e3/tello-tello_driver_node-2*.log
[ INFO] [1652619227.744957891]: Could not find goal transform for 1.06665 seconds. Exception:"base_link" passed to lookupTransform argument target_frame does not exist. 

[ INFO] [1652619227.795324530]: Could not find goal transform for 1.11701 seconds. Exception:"base_link" passed to lookupTransform argument target_frame does not exist. 

[ INFO] [1652619227.845530345]: Could not find goal transform for 1.16722 seconds. Exception:"base_link" passed to lookupTransform argument target_frame does not exist. 
```
That last message just keeps repeating.

**Comment by yoraish** [comment]
Hi! 
Are you working on Ubuntu? From your terminal prompt, it seems like you ran your commands on a MacBook. 
If this is the case, I may not be able to help much, I am sorry. Otherwise, let's proceed :).

* I am using version 3.3.1 on an Ubuntu 16.04 machine. 
* It seems like you have multiple versions of OpenCV installed, which could cause problems.
    * The signature of a method is the order and types of its arguments. The signature is not the same between versions of OpenCV. For example, see the diff between 3.3.1 and 3.2 https://www.diffchecker.com/4ZiTirGt . This difference should not be problematic for our purposes, however.
* From the error message, it seems like you are unable to run `tello_driver` properly due to a Python issue. How did you install it, by the way? Did you follow the instructions in the README? The TelloPy package (that is used by  `tello_driver` is written for Python2.x, and [uses old-style classes](https://stackoverflow.com/questions/62988598/python-super-argument-1-must-be-type-not-classobj). Therefore, I think that your ROS distro is using Python3.x. Your ROS is Melodic, so maybe `echo $ROS_PYTHON_VERSION` would shed light on the problem?
* The outputs in the form of `could not find goal transform...` are okay :).
